#!/bin/bash
set -e

export PATH="$PWD/bin:$PATH"

(
  mkdir -p bin
  cd "src/gosub"
  go build -o "../../bin/gosub" .
)

function sync_package() {
  bosh_pkg=${1}

  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      cat spec | grep -v '# gosub'

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
        if ls ../../src/${package}/*.s >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/*.s # gosub/g'
        fi
        if ls ../../src/${package}/**/*.c >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/**\/*.c # gosub/g'
        fi
        if ls ../../src/${package}/**/*.h >/dev/null 2>&1; then
          echo ${package} | sed -e 's/\(.*\)/  - \1\/**\/*.h # gosub/g'
        fi
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package winc                  -app  code.cloudfoundry.org/winc/cmd/winc
sync_package winc-network-hns-acls -app  code.cloudfoundry.org/winc/cmd/winc-network
sync_package groot                 -app  code.cloudfoundry.org/groot-windows
sync_package diff-exporter         -app  code.cloudfoundry.org/diff-exporter
sync_package cert-injector         -app  code.cloudfoundry.org/cert-injector
sync_package certsplitter-fs       -app  code.cloudfoundry.org/certsplitter/cmd/certsplitter
